{
  "openapi": "3.0.0",
  "info": {
    "title": "Social Media JWT Rest Api",
    "description": "API Rest de media social para cadastro e login de usuarios, e criação e interação de posts",
    "contact": {
      "linkedin": "https://www.linkedin.com/in/joaov1ct0r/"
    },
    "version": "1.0.0"
  },
  "paths": {
    "/api/users/register": {
      "post": {
        "summary": "Cadastro de usuarios",
        "description": "Rota para cadastro de novos usuarios",
        "tags": ["User"],
        "parameters": [
          {
            "email": "user@mail.com",
            "description": "Email do usuario a cadastrado",
            "in": "body",
            "required": true
          },
          {
            "name": "User da Silva",
            "description": "Nome do usuario a ser cadastrado",
            "in": "body",
            "required": true
          },
          {
            "bornAt": "28/06/2022",
            "description": "Data de nascimento do usuario a ser cadastrado",
            "in": "body",
            "required": true
          },
          {
            "password": "senha1234",
            "description": "Senha do usuario a ser cadastrado",
            "in": "body",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#components/schemas/User"
              },
              "examples": {
                "user": {
                  "value": {
                    "email": "user@mail.com",
                    "name": "user sobrenome",
                    "bornAt": "28/06/2022",
                    "password": "senha1234"
                  }
                }
              }
            }
          }
        }
      },
      "responses": {
        "500": {
          "description": "Internal Server Error"
        },
        "400": {
          "description": "Bad Request"
        },
        "201": {
          "description": "Created",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "$ref": "#components/schemas/User"
              }
            }
          }
        }
      }
    },
    "/api/users/login": {
      "post": {
        "summary": "Login de usuarios",
        "description": "Rota para Login de usuarios",
        "tags": ["User"],
        "parameters": [
          {
            "email": "user@mail.com",
            "description": "Email do usuario a ser realizar login",
            "in": "body",
            "required": true
          },
          {
            "password": "senha1234",
            "description": "Senha do usuario a relizar login",
            "in": "body",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#components/schemas/User"
              },
              "examples": {
                "user": {
                  "value": {
                    "email": "user@mail.com",
                    "password": "senha1234"
                  }
                }
              }
            }
          }
        }
      },
      "responses": {
        "500": {
          "description": "Internal Server Error"
        },
        "404": {
          "description": "Not Found"
        },
        "401": {
          "description": "Unathorized"
        },
        "400": {
          "description": "Bad Request"
        },
        "200": {
          "description": "Ok"
        }
      }
    },
    "/api/users/edit": {
      "put": {
        "summary": "Edição de usuarios",
        "description": "Rota para editar dados de usuarios cadastrados",
        "tags": ["User"],
        "parameters": [
          {
            "email": "user@mail.com",
            "description": "Novo email do usuario a ser alterado",
            "in": "body",
            "required": true
          },
          {
            "name": "User da Silva",
            "description": "Novo nome do usuario a ser alterado",
            "in": "body",
            "required": true
          },
          {
            "bornAt": "28/06/2022",
            "description": "Nova data de nascimento do usuario a ser alterado",
            "in": "body",
            "required": true
          },
          {
            "password": "senha1234",
            "description": "Nova senha do usuario a ser alterado",
            "in": "body",
            "required": true
          }
        ],
        "security": [{ "bearerAuth": []}] ,
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#components/schemas/User"
              },
              "examples": {
                "user": {
                  "value": {
                    "email": "user@mail.com",
                    "name": "user sobrenome",
                    "bornAt": "28/06/2022",
                    "password": "senha1234"
                  }
                }
              }
            }
          }
        }
      },
      "responses": {
        "500": {
          "description": "Internal Server Error"
        },
        "401": {
          "description": "Unathorized"
        },
        "400": {
          "description": "Bad Request"
        },
        "204": {
          "description": "No Content"
        }
      }
    },
    "/api/users/delete": {
      "delete": {
        "summary": "Exclusão de usuarios",
        "description": "Rota para deletar usuarios cadastrados",
        "tags": ["User"],
        "security": [{ "bearerAuth": []}] ,
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#components/schemas/User"
              },
              "examples": {
                "user": {
                  "value": {}
                }
              }
            }
          }
        }
      },
      "responses": {
        "500": {
          "description": "Internal Server Error"
        },
        "401": {
          "description": "Unathorized"
        },
        "400": {
          "description": "Bad Request"
        },
        "204": {
          "description": "No Content"
        }
      }
    },
    "/api/users/user": {
      "get": {
        "summary": "Visualização de usuario",
        "description": "Rota para visualizar usuario cadastrado",
        "tags": ["User"],
        "parameters": [
          {
            "email": "user@mail.com",
            "description": "Email do usuario a ser buscado",
            "in": "body",
            "required": true
          }
        ],
        "security": [{ "bearerAuth": []}] ,
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#components/schemas/User"
              },
              "examples": {
                "user": {
                  "value": {
                    "email": "user@mail.com"
                  }
                }
              }
            }
          }
        }
      },
      "responses": {
        "500": {
          "description": "Internal Server Error"
        },
        "404": {
          "description": "Not Found"
        },
        "401": {
          "description": "Unathorized"
        },
        "400": {
          "description": "Bad Request"
        },
        "200": {
          "description": "Ok"
        }
      }
    },
    "/api/users/users": {
      "get": {
        "summary": "Visualização de usuarios",
        "description": "Rota para visualizar todos os usuario cadastrado",
        "tags": ["User"],
        "security": [{ "bearerAuth": []}] ,
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#components/schemas/User"
              },
              "examples": {
                "user": {
                  "value": {}
                }
              }
            }
          }
        }
      },
      "responses": {
        "500": {
          "description": "Internal Server Error"
        },
        "401": {
          "description": "Unathorized"
        },
        "400": {
          "description": "Bad Request"
        },
        "200": {
          "description": "Ok"
        }
      }
    },
    "/api/posts/register": {
      "post": {
        "summary": "Criação de novos Posts",
        "description": "Rota para criar novos posts",
        "tags": ["Post"],
        "parameters": [
          {
            "content": "Conteudo",
            "description": "Conteudo do Post a ser criado",
            "in": "body",
            "required": true
          }
        ],
        "security": [{ "bearerAuth": []}] ,
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#components/schemas/Post"
              },
              "examples": {
                "post": {
                  "value": {
                    "content": "Comentario"
                  }
                }
              }
            }
          }
        }
      },
      "responses": {
        "500": {
          "description": "Internal Server Error"
        },
        "404": {
          "description": "Not Found"
        },
        "401": {
          "description": "Unathorized"
        },
        "400": {
          "description": "Bad Request"
        },
        "201": {
          "description": "Created"
        }
      }
    },
    "/api/posts/edit": {
      "put": {
        "summary": "Edição de Posts",
        "description": "Rota para editar posts",
        "tags": ["Post"],
        "parameters": [
          {
            "content": "Conteudo",
            "description": "Novo conteudo do post a ser alterado",
            "in": "body",
            "required": true
          },
          {
            "postId": "1",
            "description": "ID do Post a ser alterado",
            "in": "body",
            "required": true
          }
        ],
        "security": [{ "bearerAuth": []}] ,
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#components/schemas/Post"
              },
              "examples": {
                "post": {
                  "value": {
                    "postId": "1",
                    "content": "Comentario"
                  }
                }
              }
            }
          }
        }
      },
      "responses": {
        "500": {
          "description": "Internal Server Error"
        },
        "404": {
          "description": "Not Found"
        },
        "401": {
          "description": "Unathorized"
        },
        "400": {
          "description": "Bad Request"
        },
        "204": {
          "description": "No Content"
        }
      }
    },
    "/api/posts/delete": {
      "delete": {
        "summary": "Deletar Posts",
        "description": "Rota para deletar posts",
        "tags": ["Post"],
        "parameters": [
          {
            "postId": "1",
            "description": "ID do post a ser excluido",
            "in": "body",
            "required": true
          }
        ],
        "security": [{ "bearerAuth": []}] ,
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#components/schemas/Post"
              },
              "examples": {
                "post": {
                  "value": {
                    "postId": "1"
                  }
                }
              }
            }
          }
        }
      },
      "responses": {
        "500": {
          "description": "Internal Server Error"
        },
        "404": {
          "description": "Not Found"
        },
        "401": {
          "description": "Unathorized"
        },
        "400": {
          "description": "Bad Request"
        },
        "204": {
          "description": "No Content"
        }
      }
    },
    "/api/posts/like": {
      "post": {
        "summary": "Likar Posts",
        "description": "Rota para Likar posts",
        "tags": ["Post"],
        "parameters": [
          {
            "postId": "1",
            "description": "ID do post a adicionar like",
            "in": "body",
            "required": true
          }
        ],
        "security": [{ "bearerAuth": []}] ,
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#components/schemas/Post"
              },
              "examples": {
                "post": {
                  "value": {
                    "postId": "1"
                  }
                }
              }
            }
          }
        }
      },
      "responses": {
        "500": {
          "description": "Internal Server Error"
        },
        "404": {
          "description": "Not Found"
        },
        "401": {
          "description": "Unathorized"
        },
        "400": {
          "description": "Bad Request"
        },
        "201": {
          "description": "Created"
        }
      }
    },
    "/api/posts/like/delete": {
      "delete": {
        "summary": "Excluir Like",
        "description": "Rota para excluir likes de posts",
        "tags": ["Post"],
        "parameters": [
          {
            "postId": "1",
            "description": "ID do post em que o like sera excluido",
            "in": "body",
            "required": true
          }
        ],
        "security": [{ "bearerAuth": []}] ,
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#components/schemas/Post"
              },
              "examples": {
                "post": {
                  "value": {
                    "postId": "1"
                  }
                }
              }
            }
          }
        }
      },
      "responses": {
        "500": {
          "description": "Internal Server Error"
        },
        "404": {
          "description": "Not Found"
        },
        "401": {
          "description": "Unathorized"
        },
        "400": {
          "description": "Bad Request"
        },
        "204": {
          "description": "Not Found"
        }
      }
    },
    "/api/posts/comment": {
      "post": {
        "summary": "Comentar Posts",
        "description": "Rota para comentar posts",
        "tags": ["Post"],
        "parameters": [
          {
            "postId": "1",
            "description": "ID do post a ser adicionado o comentario",
            "in": "body",
            "required": true
          },
          {
            "comment": "Comentario",
            "description": "Comentario a ser criado no post",
            "in": "body",
            "required": true
          }
        ],
        "security": [{ "bearerAuth": []}] ,
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#components/schemas/Post"
              },
              "examples": {
                "post": {
                  "value": {
                    "postId": "1",
                    "comment": "Comentario"
                  }
                }
              }
            }
          }
        }
      },
      "responses": {
        "500": {
          "description": "Internal Server Error"
        },
        "404": {
          "description": "Not Found"
        },
        "401": {
          "description": "Unathorized"
        },
        "400": {
          "description": "Bad Request"
        },
        "201": {
          "description": "Created"
        }
      }
    },
    "/api/posts/comment/edit": {
      "put": {
        "summary": "Edição de comentarios em Posts",
        "description": "Rota para editar comentarios em posts",
        "tags": ["Post"],
        "security": [{ "bearerAuth": []}] ,
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#components/schemas/Post"
              },
              "examples": {
                "post": {
                  "value": {
                    "postId": "1",
                    "commentId": "2",
                    "comment": "novo comentario"
                  }
                }
              }
            }
          }
        }
      },
      "responses": {
        "500": {
          "description": "Internal Server Error"
        },
        "404": {
          "description": "Not Found"
        },
        "401": {
          "description": "Unathorized"
        },
        "400": {
          "description": "Bad Request"
        },
        "204": {
          "description": "No Content"
        }
      }
    },
    "/api/posts/comment/delete": {
      "delete": {
        "summary": "Remoção de comentarios em Posts",
        "description": "Rota para remover comentarios em posts",
        "tags": ["Post"],
        "security": [{ "bearerAuth": []}] ,
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#components/schemas/Post"
              },
              "examples": {
                "post": {
                  "value": {
                    "postId": "1",
                    "commentId": "2"
                  }
                }
              }
            }
          }
        }
      },
      "responses": {
        "500": {
          "description": "Internal Server Error"
        },
        "404": {
          "description": "Not Found"
        },
        "401": {
          "description": "Unathorized"
        },
        "400": {
          "description": "Bad Request"
        },
        "204": {
          "description": "No Content"
        }
      }
    },
    "/api/posts/posts": {
      "get": {
        "summary": "Visualização de Posts",
        "description": "Rota para visualizar todos os posts",
        "tags": ["Post"],
        "security": [{ "bearerAuth": []}] ,
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#components/schemas/Post"
              },
              "examples": {
                "post": {
                  "value": {}
                }
              }
            }
          }
        }
      },
      "responses": {
        "500": {
          "description": "Internal Server Error"
        },
        "401": {
          "description": "Unathorized"
        },
        "400": {
          "description": "Bad Request"
        },
        "200": {
          "description": "Ok"
        }
      }
    },
    "/api/posts/post": {
      "get": {
        "summary": "Visualização de Post",
        "description": "Rota para visualizar post",
        "tags": ["Post"],
        "parameters": [
          {
            "postId": "1",
            "description": "ID do post a ser buscado",
            "in": "body",
            "required": true
          }
        ],
        "security": [{ "bearerAuth": []}] ,
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#components/schemas/Post"
              },
              "examples": {
                "post": {
                  "value": {
                    "postId": "1"
                  }
                }
              }
            }
          }
        }
      },
      "responses": {
        "500": {
          "description": "Internal Server Error"
        },
        "404": {
          "description": "Not Found"
        },
        "401": {
          "description": "Unathorized"
        },
        "400": {
          "description": "Bad Request"
        },
        "200": {
          "description": "Ok"
        }
      }
    },
    "/api/admin/user/edit": {
      "put": {
        "summary": "Edição de dados do usuario",
        "description": "Rota para admin editar dados do usuario",
        "tags": ["Admin"],
        "parameters": [
          {
            "userEmail": "user@mail.com",
            "in": "body",
            "description": "Email do usuario a ser alterado",
            "required": true
          },
          {
            "userNewEmail": "user51@mail.com.br",
            "in": "body",
            "description": "Novo email do usuario",
            "required": true
          },
          {
            "userNewName": "User da Silva Atualizado",
            "in": "body",
            "description": "Novo nome do usuario",
            "required": true
          },
          {
            "userNewBornAt": "02/01/1990",
            "in": "body",
            "description": "Novo data de nascimento do usuario",
            "required": true
          },
          {
            "userNewPassword": "password123456",
            "in": "body",
            "description": "Nova senha do usuario",
            "required": true
          }
        ],
        "security": [{ "bearerAuth": []}] ,
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#components/schemas/Admin"
              },
              "examples": {
                "post": {
                  "value": {
                    "userEmail": "user@mail.com",
                    "userNewEmail": "user51@mail.com.br",
                    "userNewName": "User da Silva Atualizado",
                    "userNewBornAt": "02/01/1990",
                    "userNewPassword": "password123456"
                  }
                }
              }
            }
          }
        }
      },
      "responses": {
        "500": {
          "description": "Internal Server Error"
        },
        "404": {
          "description": "Not Found"
        },
        "401": {
          "description": "Unathorized"
        },
        "400": {
          "description": "Bad Request"
        },
        "204": {
          "description": "No Content"
        }
      }
    },
    "/api/admin/user/delete": {
      "delete": {
        "summary": "Excluir usuarios",
        "description": "Rota para admin excluir usuarios",
        "tags": ["Admin"],
        "parameters": [
          {
            "userEmail": "user@mail.com",
            "description": "Email do usuario a ser excluido",
            "in": "body",
            "required": true
          }
        ],
        "security": [{ "bearerAuth": []}] ,
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#components/schemas/Admin"
              },
              "examples": {
                "post": {
                  "value": {
                    "userEmail": "user@mail.com"
                  }
                }
              }
            }
          }
        }
      },
      "responses": {
        "500": {
          "description": "Internal Server Error"
        },
        "404": {
          "description": "Not Found"
        },
        "401": {
          "description": "Unathorized"
        },
        "400": {
          "description": "Bad Request"
        },
        "204": {
          "description": "No Content"
        }
      }
    },
    "/api/admin/post/delete": {
      "delete": {
        "summary": "Excluir Post",
        "description": "Rota para admin excluir posts de usuarios",
        "tags": ["Admin"],
        "parameters": [
          {
            "postId": "1",
            "in": "body",
            "description": "Id do Post a ser excluido",
            "required": true
          }
        ],
        "security": [{ "bearerAuth": []}] ,
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#components/schemas/Admin"
              },
              "examples": {
                "post": {
                  "value": {
                    "postId": "1"
                  }
                }
              }
            }
          }
        }
      },
      "responses": {
        "500": {
          "description": "Internal Server Error"
        },
        "404": {
          "description": "Not Found"
        },
        "401": {
          "description": "Unathorized"
        },
        "400": {
          "description": "Bad Request"
        },
        "204": {
          "description": "No Content"
        }
      }
    }
  },
  "components": {
    "schemas": {
      "User": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "bornAt": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        }
      },
      "Post": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "author": {
            "type": "string"
          },
          "content": {
            "type": "string"
          },
          "userId": {
            "type": "string"
          },
          "postId": {
            "type": "string"
          },
          "comment": {
            "type":  "string"
          },
          "commentId": {
            "type": "string"
          }
        }
      },
      "Admin": {
        "type": "object",
        "properties": {
          "userEmail": {
            "type": "string"
          },
          "userNewEmail": {
            "type": "string"
          },
          "userNewName": {
            "type": "string"
          },
          "userNewBornAt": {
            "type": "string"
          },
          "UserNewPassword": {
            "type": "string"
          },
          "postId": {
            "type": "string"
          }
        }
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
